export const OT_TIME = 20 * 60;
export const ROUND1_VIDEO = 25 * 60;
export const ROUND1_INVEST = 10 * 60;
export const ROUND2_VIDEO = 25 * 60;
export const ROUND2_INVEST = 10 * 60;
export const ROUND3_VIDEO = 25 * 60;
export const ROUND3_INVEST = 10 * 60;
export const START_TIME = 1611060030000;

export const ACC_ROUND1_VIDEO_OFFSET = ROUND1_VIDEO;
export const ACC_ROUND1_INVEST_OFFSET = ACC_ROUND1_VIDEO_OFFSET + ROUND1_INVEST;
export const ACC_ROUND2_VIDEO_OFFSET = ACC_ROUND1_INVEST_OFFSET + ROUND2_VIDEO;
export const ACC_ROUND2_INVEST_OFFSET = ACC_ROUND2_VIDEO_OFFSET + ROUND2_INVEST;
export const ACC_ROUND3_VIDEO_OFFSET = ACC_ROUND2_INVEST_OFFSET + ROUND3_VIDEO;
export const ACC_ROUND3_INVEST_OFFSET = ACC_ROUND3_VIDEO_OFFSET + ROUND3_INVEST;
